flags: {}
packages:
- '.'
- location:
    git: https://github.com/bitemyapp/esqueleto.git
    commit: 08c9b4cdf977d5bcd1baba046a007940c1940758
  extra-dep: true
- location:
    git: https://github.com/ralphmorton/nano-http.git
    commit: bfccf7011964fcd8a12f7bcbf20ac5ef06eb4ede
  extra-dep: true
- location:
    git: https://github.com/collegevine/rollbar.git
    commit: 08d7405292d71b94ea3c0562716330e77cfb93d8
  extra-dep: true
# from https://github.com/shmish111/purescript-bridge/tree/aeson-fix
# also, see: https://github.com/eskimor/purescript-bridge/issues/44
- location:
    git: https://github.com/shmish111/purescript-bridge.git
    commit: dc500a47c8330526a78c5cfac84ddb923cd5c8a5
  extra-dep: true
extra-deps:
- amazonka-1.6.0
- amazonka-core-1.6.0
- amazonka-s3-1.6.0
- katip-0.5.4.0
- servant-auth-0.3.2.0
- servant-auth-server-0.4.0.0
- servant-multipart-0.11.2
- irc-core-2.5.0
- HDBC-postgresql-2.3.2.6@sha256:6e1636b0414ae7b028a01f1a90cf3e28c14f1df7867cf2615d5357d9abcd6279
- dbmigrations-2.0.0@sha256:1e3bd62ca980659d27b6bc7b00e58ae0e2bf7781e3859f440b7c005c46037075
- yaml-light-0.1.4@sha256:838b509c3a895339eea42b6524f46ba4e59c33e9f43537123cdaedfea09ca58d
- HsSyck-0.53@sha256:a987ae2163811bdebfd4f2e2dcb7c75e9d2d68afd97d196f969d6a74786e43da
resolver: lts-12.26

#extra-include-dirs:
#- /usr/local/opt/openssl/include
#extra-lib-dirs:
#- /usr/local/opt/openssl/lib
